### ISSUE TITLE
Restore Restart Setting for Nox Player 6.6.1.2

### ISSUE THREAD

**Issue by dbzdivik** [tmarenko/mff_auto#6]
In Nox Player Setting Goto to Interface Setting and Drag "Close All Application" icon before "Screenshot icon" and NOX will set Ctrl+7 to Close all application.

![image](https://user-images.githubusercontent.com/7036189/94767223-77e8fe00-03c9-11eb-876c-c0c66e8d5936.png)

![image](https://user-images.githubusercontent.com/7036189/94767331-b41c5e80-03c9-11eb-8f0e-5adee1956ddb.png)

**Comment by dbzdivik** [comment]
Also, is there any way around if the laptop screen gets down or display off then Bot also stop working.

**Comment by dbzdivik** [comment]
> As far as I know - no, there isn't. WinAPI can't get emulator's screen if emulator is minimized or display is off.
> The only way is to change Windows Power Settings to not turn off display when lid is closed => display will be always on.

https://stackoverflow.com/a/57647169

**Comment by tmarenko** [comment]
> https://stackoverflow.com/a/57647169

Thanks, I'll add this soon. Sure, preventing Windows going to sleep mode is a mush have feature.

**Comment by dbzdivik** [comment]
`2020-10-02 07:21:32,997 - root - WARNING - NoxPlayer 6.6.1.2: can't find config `toolbar_close_all_index` in NoxPlayer's config file.`

**Comment by tmarenko** [comment]
Could you please check all `.ini` files in path `%APPDATA%\..\Local\Nox`?
Does any of these files contains line with `toolbar_close_all_index` in it?

**Comment by dbzdivik** [comment]
Local\Nox\conf.ini 

`[toolbar_setting]
display_toolbar_add_apk=true
display_toolbar_clip_cursor=true
display_toolbar_close_all=true`

**Comment by tmarenko** [comment]
Try to change order of toolbar and save settings.

**Comment by tmarenko** [comment]
> https://stackoverflow.com/a/57647169

Done in 84c19315430b90824548adcb2be46fe5023be479

**Comment by dbzdivik** [comment]
> Try to change order of toolbar and save settings.

Share ur's NOX Conf File.
PFA mine

[conf.txt](https://github.com/tmarenko/mff_auto/files/5321908/conf.txt)

**Comment by tmarenko** [comment]
I've tried to install NoxPlayer 6.6.1.3 on pure Windows VM.
This is config file after installation and first start (no `toolbar_close_all_index` in config file):
[conf.txt](https://github.com/tmarenko/mff_auto/files/5323107/conf.txt)

After this I've edited order of toolbar in Settings:
![image](https://user-images.githubusercontent.com/31345208/95014263-6d8b6600-064e-11eb-84a9-892fcdbbd235.png)

And config file became this one (with `toolbar_close_all_index=1`):
[conf.txt](https://github.com/tmarenko/mff_auto/files/5323112/conf.txt)

**Comment by tmarenko** [comment]
It's actually possible to manually add this line `toolbar_close_all_index=%any_number_from_1_to_10%` to config file and restart NoxPlayer to apply changes. 
Maybe this should be added to be done first time when you set up bot.

**Comment by dbzdivik** [comment]
> I've tried to install NoxPlayer 6.6.1.3 on pure Windows VM.
> This is config file after installation and first start (no `toolbar_close_all_index` in config file):
> [conf.txt](https://github.com/tmarenko/mff_auto/files/5323107/conf.txt)

Ok BTW where did you get 6.6.1.3 I think the latest is 6.6.1.2...

> After this I've edited order of toolbar in Settings:
> ![image](https://user-images.githubusercontent.com/31345208/95014263-6d8b6600-064e-11eb-84a9-892fcdbbd235.png)
> 
> And config file became this one (with `toolbar_close_all_index=1`):
> [conf.txt](https://github.com/tmarenko/mff_auto/files/5323112/conf.txt)

But my config file still doesn't have `toolbar_close_all_index=1` or anything like this

**Comment by tmarenko** [comment]
> But my config file still doesn't have toolbar_close_all_index=1 or anything like this

Check if file can be overwritten (Read-only off)
![image](https://user-images.githubusercontent.com/31345208/95017850-5d7e8100-0664-11eb-85d8-4e52d5366d89.png)

**Comment by dbzdivik** [comment]
> Check if file can be overwritten (Read-only off)

Yeah Read-only is off

**Comment by tmarenko** [comment]
Can you try this build? Just made a copy of your bot's folder and paste archive contents in it:
[build.zip](https://github.com/tmarenko/mff_auto/files/5328522/build.zip)

You can remove `settings/gui/game.json` and run emulator setup again 
or use this menu:
![image](https://user-images.githubusercontent.com/31345208/95103862-d4d41380-073d-11eb-935e-f9b0e1231e6e.png)

You need to restart NoxPlayer after that. And check `conf.ini` file again.

**Comment by dbzdivik** [comment]
Hmm Now you need to add restart button in Bot Itself. BTW why not setting index to 8 via bot ?

1st
>2020-10-06 09:06:03,617 - root - WARNING - NoxPlayer 6.6.1.2: can't find config `toolbar_close_all_index` in NoxPlayer's config file.
2020-10-06 09:06:41,766 - game - DEBUG - Loading circle is on screen.
2020-10-06 09:06:42,861 - game - DEBUG - Loading circle is on screen.
2020-10-06 09:06:43,995 - game - DEBUG - Loading circle is on screen.
2020-10-06 09:06:51,760 - game - DEBUG - Loading circle is on screen.
2020-10-06 09:07:05,243 - root - INFO - NoxPlayer: saved config file clone_Nox_1_conf.ini. Need to restart emulator to apply changes.
2020-10-06 09:07:59,573 - root - DEBUG - NoxPlayer 6.6.1.2: found `Close App` shortcut at position 10

2nd
>2020-10-06 09:08:40,949 - root - DEBUG - NoxPlayer None: found `Close App` shortcut at position 11
2020-10-06 09:08:40,949 - root - WARNING - NoxPlayer None: shortcut position is greater than 10, can't be casted via keyboard. Try to open NoxPlayer settings -> `Interface settings` and then change position of `Close all apps` toolbar and then restart the bot.
2020-10-06 09:08:40,950 - root - DEBUG - Initialized NoxWindow object with name NoxPlayer version 6.6.1.2 and resolution (997, 561); main window: (2, 32, 999, 593), parent: (639, 240)
2020-10-06 09:08:40,951 - root - DEBUG - NoxPlayer 6.6.1.2: found `Close App` shortcut at position 11
2020-10-06 09:08:40,951 - root - WARNING - NoxPlayer 6.6.1.2: shortcut position is greater than 10, can't be casted via keyboard. Try to open NoxPlayer settings -> `Interface settings` and then change position of `Close all apps` toolbar and then restart the bot.
2020-10-06 09:08:40,974 - main - INFO - Team number for TimeLine battles : 1

3rd
>2020-10-06 09:09:44,662 - root - DEBUG - Creating 2 Tesseract API(s) with 'mff+eng' language.
2020-10-06 09:09:45,309 - root - DEBUG - NoxPlayer None: found `Close App` shortcut at position 8

**Comment by dbzdivik** [comment]
Also Instead of Placing a Menu Bar, it could be placed via buttons before the info section with Restart Bot Option

GroupBox1: - Info Section
GroupBox2:- Bot Function { Restartable Nox, Restart Bot, Restart Game} <= Button Forms
GroupBox3: - Autoplay++ {What is the use of this function I never tried}

**Comment by tmarenko** [comment]
> Hmm Now you need to add restart button in Bot Itself

Do I need really? =) You'd need to restart only once (at the first setup), so not worth it. Sure you can do it manually.

> BTW why not setting index to 8 via bot ?

Does it matter? Bot still would get any index from config file.

> 1st 2nd 3rd

I don't understand this logs. Is it from different Nox's clones?

> GroupBox3: - Autoplay++ {What is the use of this function I never tried}

It enables `ManualBattleBot` to recognize battles and fight. Basically, you can use in 'World Event' mission or while doing `Shadowlands` - bot would fight in the battles by itself.

**Comment by dbzdivik** [comment]
Never Mind Everything is Working fine... Cheers

**Comment by dbzdivik** [comment]
![image](https://user-images.githubusercontent.com/7036189/95708231-5adde600-0c79-11eb-8b20-2a9efd8d39b1.png)

**Comment by tmarenko** [comment]
> the bot is unable to restart the game while checking for Farming Bios

For some reason NoxPlayer's control stops receiving signals after a while. Found more stable control, fixed in 5f5d0a452d1521ae11b616e480c52fafed465c16

**Comment by dbzdivik** [comment]
> > For some reason NoxPlayer's control stops receiving signals after a while. Found more stable control, fixed in [5f5d0a4](https://github.com/tmarenko/mff_auto/commit/5f5d0a452d1521ae11b616e480c52fafed465c16)
> 
> Still losing control after 10-20 restarts =\ Don't know why. Nothing was changed in restart logic but suddenly it started to fail.
> 
> P.S. Even hitting shortcut manually doesn't work.

Hmm, why not add a check that If on hitting close game is closed or not?

**Comment by tmarenko** [comment]
I've tested it on fresh NoxPlayer 6.3.0.5. Restarting is working fine and without any troubles.
Are you using one bot's instance (and emulator) at a time or more?

> Hmm, why not add a check that If on hitting game is closed or not?

Not sure how to consistently check it. There is no 100% mark that application was really closed (as far as I know).

**Comment by dbzdivik** [comment]
"C:\Program Files\Nox\bin\Nox.exe" -clone:Nox_1 -startPackage:com.netmarble.mherosgb

Directly Open MFF via BOT instead of open first Play Nox start Game and then start Bot.
